spring:
    datasource:
        url: jdbc:mysql://localhost:3306/youran-chart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
logging:
    level:
        root: info
        java:
            sql: debug
        com:
            youran: trace
swagger:
    enabled: true
youran:
    # 缓存数据目录，用来临时存储模板文件、生成的代码文件，每次启动都会清空该目录
    data-dir: D:\\youran
    # 启动时初始化用户表
    default-user-init: true
    # 0:非开发模式 1:开发模式-全量替换 2:开发模式-增量替换
    dev-mode: 0
    # 开发模式下，自动生成代码到该路径
    dev-project-dir: D:\\workspace_cbb\\auto
    # 是否启用登录校验，一般不启用，除非部署到公开网络环境，不想让外人访问
    security-enabled: false
