server:
    servlet:
        context-path: /
        encoding:
            force: true
    port: 8088
spring:
    application:
        name: youran-generate
    profiles:
        active: local
    security:
        user:
            name: admin
            password: 123456
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 100MB
springfox:
    documentation:
        enabled: true
mybatis:
    config-location: classpath:mybatis-config.xml

youran:
    auto-branch-name: auto
    aes-key: orpNB6YGbiiDcrrubk2rFQ==
    version: 3.5.0
    api-path: /api
    ws-api-path: /ws_api
    security-enabled: false
    team-enabled: false

